scrape_configs:
  - job_name: 'ssllabs-exporter'
    scrape_interval: 10m
    scrape_timeout: 10m
    metrics_path: /probe
    kubernetes_sd_configs:
      - role: ingress
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: ssllabs-exporter  # change this to the FQDN of ssllabs-exporter
      - source_labels: [__param_target]
        target_label: instance
      - action: labelmap
        regex: __meta_kubernetes_ingress_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_ingress_name]
        target_label: kubernetes_name
