scrape_configs:
  - job_name: 'ssllabs-exporter'
    scrape_interval: 10m
    scrape_timeout: 10m
    metrics_path: /probe
    static_configs:
    - targets:
      - duckduckgo.com
      - stackoverflow.com
      - prometheus.io
      - a-domain-that-will-fail.somewhere
      - github.com
      - ssllabs.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: ssllabs-exporter  # change this to the FQDN of ssllabs-exporter
      - source_labels: [__param_target]
        target_label: instance
