{
 "title": "SSLLabs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "target",
    "label": "Target",
    "query": "label_values(ssllabs_probe_success, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Grade",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ssllabs_grade{instance=~\"$target\"}",
     "legendFormat": "{{ instance }} [{{ grade }}]"
    }
   ]
  },
  {
   "title": "Probe Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ssllabs_probe_success{instance=~\"$target\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Probe Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "dateTimeAsUS" }
   ],
   "targets": [
    {
     "expr": "ssllabs_grade_age_seconds{instance=~\"$target\"} * 1000",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ssllabs_probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}