apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ssllabs-exporter
  labels:
    app: ssllabs-exporter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ssllabs-exporter
    spec:
      containers:
        - name: ssllabs-exporter
          image: "anasaso/ssllabs_exporter:latest"
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 19115
          livenessProbe:
            httpGet:
              path: /
              port: 19115
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
